# PostgreSQL. Versions 9.5 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/opt/homebrew/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER", "admin") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "1234") %>
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>

development:
  primary:
    <<: *default
    database: <%= ENV.fetch("POSTGRES_DB", "petunia_development") %>
  cache:
    <<: *default
    database: <%= ENV.fetch("POSTGRES_DB", "petunia_development") %>_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: <%= ENV.fetch("POSTGRES_DB", "petunia_development") %>_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: <%= ENV.fetch("POSTGRES_DB", "petunia_development") %>_cable
    migrations_paths: db/cable_migrate

test:
  primary:
    <<: *default
    database: <%= ENV.fetch("POSTGRES_DB_TEST", "petunia_test") %>

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV.fetch("POSTGRES_DB", "petunia_production") %>
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *primary_production
    database: <%= ENV.fetch("POSTGRES_DB", "petunia_production") %>_cache
    url: <%= ENV.fetch("SOLID_CACHE_DATABASE_URL") { ENV["DATABASE_URL"] } %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: <%= ENV.fetch("POSTGRES_DB", "petunia_production") %>_queue
    url: <%= ENV.fetch("SOLID_QUEUE_DATABASE_URL") { ENV["DATABASE_URL"] } %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: <%= ENV.fetch("POSTGRES_DB", "petunia_production") %>_cable
    url: <%= ENV.fetch("SOLID_CABLE_DATABASE_URL") { ENV["DATABASE_URL"] } %>
    migrations_paths: db/cable_migrate

